# Generated by Django 5.1.7 on 2026-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
