# Generated by Django 5.1.7 on 2026-04-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
