# Generated by Django 5.1.7 on 2026-05-01 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
