# Generated by Django 5.1.7 on 2026-05-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
