# Generated by Django 5.1.7 on 2026-05-14 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_room_uuid_alter_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 10, 31, 42, 216131, tzinfo=datetime.timezone.utc)),
        ),
    ]
