# Generated by Django 5.1.7 on 2026-06-23 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 10, 8, 54, 753768, tzinfo=datetime.timezone.utc)),
        ),
    ]
